/*

  DO NOT EDIT THIS FILE

  This is a template for use with your Unit, to use as a base, provided as an example.

*/
#include <unit/simple_sub/unit_base.h>

class simple_sub : public unit::simple_sub::Base {
  simple_sub() {

  }


    virtual unit::simple_sub::SimpleSub::Output SimpleSub(const unit::simple_sub::SimpleSub::Input& input) override;

};