/*

  DO NOT EDIT THIS FILE

  This is a template for use with your Unit, to use as a base, provided as an example.

*/

#include <simple_pub.h>

using namespace unit::simple_pub;


SimplePub::Output simple_pub::SimplePub(const SimplePub::Input& input) {
    static_assert(false, "Implement me");
}
