/*

  DO NOT EDIT THIS FILE

  This is a template for use with your Unit, to use as a base, provided as an
  example.

*/
#include <unit/pybind_test/unit_base.h>
class pybind_test : public unit::pybind_test::Base {
public:
  pybind_test(const Args &args,
              const std::optional<std::string_view> &name_override = {})
      : unit::pybind_test::Base(args, name_override) {}
  virtual unit::pybind_test::InprocTestTrigger::Output InprocTestTrigger(
      const unit::pybind_test::InprocTestTrigger::Input &input) override;
  virtual unit::pybind_test::InprocTest::Output
  InprocTest(const unit::pybind_test::InprocTest::Input &input) override;
};