/*

  DO NOT EDIT THIS FILE

  This is a template for use with your Unit, to use as a base, provided as an
  example.

*/
#include <pybind_test.h>
using namespace unit::pybind_test;
InprocTestTrigger::Output
pybind_test::InprocTestTrigger(const InprocTestTrigger::Input &input) {
  static_assert(false, "Implement me");
}
InprocTest::Output pybind_test::InprocTest(const InprocTest::Input &input) {
  static_assert(false, "Implement me");
}
StereoMatch::Output pybind_test::StereoMatch(const StereoMatch::Input &input) {
  static_assert(false, "Implement me");
}
TimeTest::Output pybind_test::TimeTest(const TimeTest::Input &input) {
  static_assert(false, "Implement me");
}
ApproxTest::Output pybind_test::ApproxTest(const ApproxTest::Input &input) {
  static_assert(false, "Implement me");
}
