/*

  DO NOT EDIT THIS FILE

  This is a template for use with your Unit, to use as a base, provided as an example.

*/

#include <wip.h>

using namespace unit::wip;


StereoMatch::Output wip::StereoMatch(const StereoMatch::Input& input) {
    static_assert(false, "Implement me");
}

TimeTest::Output wip::TimeTest(const TimeTest::Input& input) {
    static_assert(false, "Implement me");
}

ApproxTest::Output wip::ApproxTest(const ApproxTest::Input& input) {
    static_assert(false, "Implement me");
}
