/*

  DO NOT EDIT THIS FILE

  This is a template for use with your Unit, to use as a base, provided as an example.

*/
#include <unit/test_unit/unit_base.h>

class test_unit : public unit::test_unit::Base {
  test_unit() {

  }


    virtual unit::test_unit::StereoMatch::Output StereoMatch(const unit::test_unit::StereoMatch::Input& input) override;

    virtual unit::test_unit::TimeTest::Output TimeTest(const unit::test_unit::TimeTest::Input& input) override;

    virtual unit::test_unit::ApproxTest::Output ApproxTest(const unit::test_unit::ApproxTest::Input& input) override;

};