/*

  DO NOT EDIT THIS FILE

  This is a template for use with your Unit, to use as a base, provided as an example.

*/
#include <unit/test_unit/unit_base.h>

class test_unit : public unit::test_unit::Base {
public:
  test_unit(std::optional<std::string> name_override = {}) 
  : unit::test_unit::Base(name_override)
  {}


  virtual unit::test_unit::StereoMatch::Output
  StereoMatch(const unit::test_unit::StereoMatch::Input &input) override;

  virtual unit::test_unit::AllTest::Output
  AllTest(const unit::test_unit::AllTest::Input &input) override;

  virtual unit::test_unit::ApproxTest::Output
  ApproxTest(const unit::test_unit::ApproxTest::Input &input) override;

  virtual unit::test_unit::TestEqualOptions::Output
  TestEqualOptions(const unit::test_unit::TestEqualOptions::Input &input) override;

  virtual unit::test_unit::TestInprocTypePub::Output
  TestInprocTypePub(const unit::test_unit::TestInprocTypePub::Input &input) override;

  virtual unit::test_unit::TestInprocTypeSubEither::Output
  TestInprocTypeSubEither(const unit::test_unit::TestInprocTypeSubEither::Input &input) override;

  virtual unit::test_unit::TestInprocTypeSubOnlyMessage::Output
  TestInprocTypeSubOnlyMessage(const unit::test_unit::TestInprocTypeSubOnlyMessage::Input &input) override;

  virtual unit::test_unit::TestInprocTypeSubOnlyInproc::Output
  TestInprocTypeSubOnlyInproc(const unit::test_unit::TestInprocTypeSubOnlyInproc::Input &input) override;

  virtual unit::test_unit::TestInprocTypeSubAccumulate::Output
  TestInprocTypeSubAccumulate(const unit::test_unit::TestInprocTypeSubAccumulate::Input &input) override;

  virtual unit::test_unit::TestInprocTypeSubAvoidPointlessConversion::Output
  TestInprocTypeSubAvoidPointlessConversion(const unit::test_unit::TestInprocTypeSubAvoidPointlessConversion::Input &input) override;

};