/*

  DO NOT EDIT THIS FILE

  This is a template for use with your Unit, to use as a base, provided as an example.

*/

#include <test_unit.h>

using namespace unit::test_unit;


StereoMatch::Output test_unit::StereoMatch(const StereoMatch::Input& input) {
    static_assert(false, "Impelement me");
}

TimeTest::Output test_unit::TimeTest(const TimeTest::Input& input) {
    static_assert(false, "Impelement me");
}

ApproxTest::Output test_unit::ApproxTest(const ApproxTest::Input& input) {
    static_assert(false, "Impelement me");
}
