/*

  DO NOT EDIT THIS FILE

  This is a template for use with your Unit, to use as a base, provided as an example.

*/

#include <test_unit.h>

using namespace unit::test_unit;


StereoMatch::Output test_unit::StereoMatch(const StereoMatch::Input& input) {
    static_assert(false, "Implement me");
}

AllTest::Output test_unit::AllTest(const AllTest::Input& input) {
    static_assert(false, "Implement me");
}

ApproxTest::Output test_unit::ApproxTest(const ApproxTest::Input& input) {
    static_assert(false, "Implement me");
}

TestEqualOptions::Output test_unit::TestEqualOptions(const TestEqualOptions::Input& input) {
    static_assert(false, "Implement me");
}

TestInprocTypePub::Output test_unit::TestInprocTypePub(const TestInprocTypePub::Input& input) {
    static_assert(false, "Implement me");
}

TestInprocTypeSubEither::Output test_unit::TestInprocTypeSubEither(const TestInprocTypeSubEither::Input& input) {
    static_assert(false, "Implement me");
}

TestInprocTypeSubOnlyMessage::Output test_unit::TestInprocTypeSubOnlyMessage(const TestInprocTypeSubOnlyMessage::Input& input) {
    static_assert(false, "Implement me");
}

TestInprocTypeSubOnlyInproc::Output test_unit::TestInprocTypeSubOnlyInproc(const TestInprocTypeSubOnlyInproc::Input& input) {
    static_assert(false, "Implement me");
}

TestInprocTypeSubAccumulate::Output test_unit::TestInprocTypeSubAccumulate(const TestInprocTypeSubAccumulate::Input& input) {
    static_assert(false, "Implement me");
}

TestInprocTypeSubAvoidPointlessConversion::Output test_unit::TestInprocTypeSubAvoidPointlessConversion(const TestInprocTypeSubAvoidPointlessConversion::Input& input) {
    static_assert(false, "Implement me");
}
